# module name, required
name: ${oc.env:MODULE_NAME, 'demo'}

# base module parameters
parameters:
  # DevMode (hot Python code reload on file change)
  dev_mode: True
  # Allows sending shutdown message to the module with the auth-key (see below)
  shutdown_auth: "shutdown"
  # enable OpenTelemetry
  # telemetry:
  #   tracing:
  #     sampling_period: 100
  #     root_span_name: pipeline
  #     provider: jaeger
  #     provider_params:
  #       service_name: demo-pipeline
  #       protocol: grpc
  #       endpoint: "http://jaeger:4317"
        # timeout: 5000 # milliseconds
        # tls:
        #   certificate: /path/to/ca.crt
        #   identity:
        #       certificate: /path/to/client.crt
        #       key: /path/to/client.key

  # pipeline processing frame parameters
  sidebar_width: 296
  frame:
    width: 1280
    height: 720
    # Add paddings to the frame before processing
  output_frame:
    codec: raw-rgba
    # encoder: nvenc
  # custom drawing on frames function
  draw_func:
    module: viags_demo.overlay
    class_name: Overlay
    kwargs:
      config_path: /opt/savant/viags_demo/area_config.yml
      sidebar_width: ${parameters.sidebar_width}
      target_obj_label: head
    # rendered_objects:
    #   peoplenet:
    #     person:
    #     face:


# pipeline definition
pipeline:
  # define pipeline's main elements
  elements:
    # primary detector element, inference is provided by the nvinfer Deepstream element
    # model type is detector (other available types are: classifier, custom)
    - element: nvinfer@detector
      # Model's name in the pipeline, mandatory
      name: head_detection
      # model definition
      model:
        format: onnx
        model_file: head.pt.onnx
        config_file: config_infer_primary_head_detection.txt
        batch_size: 1
        workspace_size: 6144

        # configuration of input data and custom preprocessing methods
        input:
          # model input layer name
          layer_name: input
          # model input layer shape
          shape: [3, 640, 640]
          # pixel scaling/normalization factor
          scale_factor: 0.0039215697906911373

        # configuration of model output
        output:
          # model output layer names
          layer_names: [output]
          converter:
            module: viags_demo.yolov9_converter
            class_name: YOLOv9Converter
            kwargs:
              confidence_threshold: 0.6
              nms_iou_threshold: 0.45
              top_k: 10
          # number of detected classes for detector model
          num_detected_classes: 1
          objects:
            - class_id: 0
              label: head

    # - element: nvtracker
    #   properties:
    #     ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
    #     ll-config-file: /opt/savant/samples/assets/tracker/config_tracker_NvDCF_perf.yml
    #     tracker-width: 960  # 640  # must be a multiple of 32
    #     tracker-height: 544  # 384
    #     display-tracking-id: 0

    # custom pyfunc element
    # - element: pyfunc
    #   module: viags_demo.object_counting
    #   class_name: ObjectCounting
    #   kwargs:
    #     config_path: /opt/savant/viags_demo/area_config.yml
    #     target_obj_label: head
    #     send_stats: False